// frontend/src/components/shared/footer/Footer.vue
﻿<template >
	<div className="footer">
		<div className="footer__wrapper">
			<a-typography-text className="footer__text">Copyright &copy;{{year}} Designed by Valentin Zadorozhniy{{' '}}</a-typography-text>
			<a href="https://t.me/Shalfei"><a-logo class="footer__icon"></a-logo></a>
		</div>
	</div>
</template>

<script setup >
	import moment from 'moment'
	import ALogo from '@app/shared/footer/svg/telegramm.svg';
	import { computed } from 'vue';

	const year = computed(() => moment().year())
</script>

<style lang="scss">
	@import '@app/App.scss';

	.footer{
		margin-top: 40px;
		background-color: $blue-color;
		width: 100%;
		height: 70px;
		display: flex;
		justify-content: center;
		align-content: center;
		&__wrapper{
			align-self: center;
			display: flex;
		}
		&__text{
			color: $white-color;
		}
		&__icon{
			margin-left: 5px;
			height: 19px;
			width: 15px;
		}
	}
</style>

// frontend/src/components/shared/footer/Footer.tsx
﻿import React from 'react'
import { Typography } from 'antd'
import Icon from '@ant-design/icons'
import { Link } from 'react-router-dom'
import MessageSvg  from './svg/telegramm.svg'

const {Text}	= Typography

import '@app/shared/footer/footer.scss'
import moment from 'moment'

interface IProps {
	
}

const Footer: React.FC<IProps> = () => {
	 return <div className='footer'>
		<div className='footer__wrapper'>
			<Text className='footer__text' >Copyright &copy;{moment().year()} Designed by Valentin Zadorozhniy{' '}</Text>	
			<Link to={'https://t.me/Shalfei'}>
				<Icon component={MessageSvg} />	
			</Link>
	 </div>
	 </div>
}

export default Footer
