// frontend/src/components/pages/userInfo/UserInfo.vue
﻿<template >
  <div>Hello World</div>
</template>

<script >
  export default {
  }
</script>

<style>
</style>



<!-- import React, { useEffect, useState }from 'react'
import { useSelector } from 'react-redux'
import { Input, Typography, Tabs, TabsProps } from 'antd'
import { useNavigate, useOutletContext, useParams } from 'react-router-dom'
import queryString from 'query-string'

import '@app/pages/userInfo/userInfo.scss'
import { RootState } from '@app/store/store'
import UserContent from './components/userContent'
import ArticlesContent from './components/articleContent'
import { INotificationAction } from '@app/shared/layout/types'

const { TextArea } = Input

const { Title } = Typography

const formItemLayout = {
	labelCol: {
		xs: { span: 24 },
		sm: { span: 4 }
	},
	wrapperCol: {
		xs: { span: 24 },
		sm: { span: 16 }
	}
}

const tailFormItemLayout = {
	wrapperCol: {
		xs: {
			span: 24,
			offset: 0
		},
		sm: {
			span: 16,
			offset: 4
		}
	}
}

const UserInfo: React.FC = () => {
	const navigate = useNavigate()
	const {username} = useParams()
	const openNotification = useOutletContext()
	const [tabQuery, setTabQuery]  = useState('')
	const userInfo = useSelector((state: RootState) => state.userInfo.data)
	const tabs: TabsProps['items'] = [
		{
			key: 'user-content',
			label: 'User Info',
			children: <UserContent /> ,
		},
		{
			key: 'articles-content',
			label: 'Articles Info',
			children: <ArticlesContent openNotification={openNotification as INotificationAction['openNotification']}/>,
		}
	]

	useEffect(() => {
		const { tab } = queryString.parse(window.location.search)
		const currentTab = tab ? `${tab}` : 'user-content'
		setTabQuery(currentTab)
		if(username){
			navigate(`/userinfo/${username}?${queryString.stringify({ tab: currentTab})}`)
		}
	}, [userInfo?.username]) 

	const onChange = (key: string) => {
		setTabQuery(key)
		navigate(`/userinfo/${username}?${queryString.stringify({ tab: key})}`)
	}

	return ( 
		<div className="user-info">
			<Tabs 
				className={'user-info__tabs'}
				defaultActiveKey="user-content"
				items={tabs}
				activeKey={tabQuery}
				onChange={onChange}
			/>
		</div>
	)
}

export default UserInfo -->

// frontend/src/components/pages/userInfo/UserInfo.tsx
﻿import React, { useEffect, useState }from 'react'
import { useSelector } from 'react-redux'
import { Input, Typography, Tabs, TabsProps } from 'antd'
import { useNavigate, useOutletContext, useParams } from 'react-router-dom'
import queryString from 'query-string'

import '@app/pages/userInfo/userInfo.scss'
import { RootState } from '@app/store/store'
import UserContent from './components/userContent'
import ArticlesContent from './components/articleContent'
import { INotificationAction } from '@app/shared/layout/types'

const { TextArea } = Input

const { Title } = Typography

const formItemLayout = {
	labelCol: {
		xs: { span: 24 },
		sm: { span: 4 }
	},
	wrapperCol: {
		xs: { span: 24 },
		sm: { span: 16 }
	}
}

const tailFormItemLayout = {
	wrapperCol: {
		xs: {
			span: 24,
			offset: 0
		},
		sm: {
			span: 16,
			offset: 4
		}
	}
}

const UserInfo: React.FC = () => {
	const navigate = useNavigate()
	const {username} = useParams()
	const openNotification = useOutletContext()
	const [tabQuery, setTabQuery]  = useState('')
	const userInfo = useSelector((state: RootState) => state.userInfo.data)
	const tabs: TabsProps['items'] = [
		{
			key: 'user-content',
			label: 'User Info',
			children: <UserContent /> ,
		},
		{
			key: 'articles-content',
			label: 'Articles Info',
			children: <ArticlesContent openNotification={openNotification as INotificationAction['openNotification']}/>,
		}
	]

	useEffect(() => {
		const { tab } = queryString.parse(window.location.search)
		const currentTab = tab ? `${tab}` : 'user-content'
		setTabQuery(currentTab)
		if(username){
			navigate(`/userinfo/${username}?${queryString.stringify({ tab: currentTab})}`)
		}
	}, [userInfo?.username]) 

	const onChange = (key: string) => {
		setTabQuery(key)
		navigate(`/userinfo/${username}?${queryString.stringify({ tab: key})}`)
	}

	return ( 
		<div className="user-info">
			<Tabs 
				className={'user-info__tabs'}
				defaultActiveKey="user-content"
				items={tabs}
				activeKey={tabQuery}
				onChange={onChange}
			/>
		</div>
	)
}

export default UserInfo
